### ISSUE TITLE
Macro broke :c / multi-monitor issue

### ISSUE THREAD

**Issue by Kalperkalping** [Barni6264/AngelMacro#1]
Macro switched to my second monitor and started spamming someone on discord with the message "r". the problem probably was not the macro but something with my computer since the macro doesnt use the mouse only the keyboard. the macro kept resetting on roblox so it can find the pixel perfect spot and to do that it needs to press escape, r, enter, which is how you send a message on discord but without the escape. not the macros fault it had something to do with me

**Comment by Barni6264** [comment]
Hello, if there were no recorded mouse movements, the program can't really switch to other monitors. However, there's an issue with multi monitor setups and the mouse/pixel location. If 2+ monitors cause the code to malfunction, that's a known issue, and I'm working on it.
I'll keep this open until I fix the issue mentioned above.

**Comment by Kalperkalping** [comment]
gameeeeeeeeeeeeee

**Comment by Barni6264** [comment]
Next release includes the fix
